name: Edge Deployment Build

on:
  push:
    branches: [main, edge]
    paths:
      - 'src/**'
      - 'Dockerfile.hardware'
      - '.github/workflows/build-edge.yml'
  workflow_dispatch:

jobs:
  build-multiarch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            arch: amd64
          - platform: linux/arm64
            arch: arm64
          - platform: linux/arm/v7
            arch: armv7
          - platform: linux/arm/v6
            arch: armv6
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=edge
            type=sha
      
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.hardware
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:edge-${{ matrix.arch }}-latest
            ghcr.io/${{ github.repository }}:edge-${{ matrix.arch }}-${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ matrix.arch }}
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ matrix.arch }},mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

  create-manifest:
    runs-on: ubuntu-latest
    needs: build-multiarch
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create multi-arch manifest
        run: |
          docker buildx imagetools create -t ghcr.io/${{ github.repository }}:edge-latest \
            ghcr.io/${{ github.repository }}:edge-amd64-latest \
            ghcr.io/${{ github.repository }}:edge-arm64-latest \
            ghcr.io/${{ github.repository }}:edge-armv7-latest \
            ghcr.io/${{ github.repository }}:edge-armv6-latest
